<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'vendor/autoload.php'; // Path to autoload.php in your project

// Send email with message
$mail = new PHPMailer(true);

try {
    //Server settings
    $mail->isSMTP();
    $mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;
    $mail->Username = 'enter your mail id'; // SMTP username (your Gmail address)
    $mail->Password = 'your smtp password '; // SMTP password (your Gmail password or App Password)
    $mail->SMTPSecure = 'tls';
    $mail->Port = 587;

    //Recipients
    $mail->setFrom('your mail here ', 'hello sir');
    $mail->addAddress("recipient mail here ");     // Add a recipient

    // Content
    $mail->isHTML(true);
    $mail->Subject = 'Important Message for you';
    $mail->Body    = 'hello sir how are yoy .<br><br>'
    
                   . '<p1>this otp is generated by devkumar-swipe </p1>';

    $mail->send();
    echo 'Email has been sent with your message.';
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}
?>
